theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
comments:
  provider: "staticman"
  # to accept the pending invitation visit: https://api.staticman.net/v1/connect/fabioperrella/fabioperrella.github.io